studyplanner/planner/urls.py
from django.urls import path
from . import views

app_name = "planner"

urlpatterns = [
    path('index/', views.subject_list, name='index'),
    path('sessions/', views.session_list, name='sessions'),
    path('test/', views.test),
    path('subjects/edit/', views.subject_edit, name='subject_edit'),
    path('delete/', views.delete_subject, name='delete_subject'),
    path('subject/add/', views.subject_create, name='subject_add'),
    path('add/', views.add_studysession, name='add_studysession'),
    path('delete-session/', views.delete_session, name='delete_session'),
    path('edit-session/', views.edit_session, name='edit_session'),
    path('api/events/', views.events_api, name='events_api'),
    path("api/update-session-date/", views.update_session_date, name="update_session_date"),

]

studyplanner/studyplanner/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('planner/', include("planner.urls")),
    path('users/', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.BASE_DIR / "static")

studyplanner/users/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('login/', view = views.log_in, name = "login"),
]

studyplanner/planner/models.py
from django.db import models
from django.utils import timezone
from recurrence.fields import RecurrenceField

# Create your models here.

class subject(models.Model):
    name = models.CharField(max_length=100, verbose_name="Name")
    color = models.CharField(max_length=13,verbose_name="Color", choices={
        "#FFADAD" : "Melon",
        "#FFD6A5" : "Sunset",
        "#FDFFB6" : "Cream",
        "#CAFFBF" : "Tea green",
        "#9BF6FF" : "Electric blue",
        "#A0C4FF" : "Jordy Blue",
        "#BDB2FF" : "Periwinkle",
        "#FF9EFF" : "Mauve",
    })

    def __str__(self):
        return self.name
    
class RecurringStudySession(models.Model):
    title = models.CharField(max_length=200)
    subject = models.ForeignKey(subject, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()
    recurrence = RecurrenceField()

class SkippedOccurrence(models.Model):
    recurring = models.ForeignKey(RecurringStudySession, on_delete=models.CASCADE)
    date = models.DateField()

    class Meta:
        unique_together = ('recurring', 'date')

    def __str__(self):
        return f"Skipped {self.date} for {self.recurring.title}"
    
class studysession(models.Model):
    subject = models.ForeignKey(subject, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    start_session = models.DateTimeField(default=timezone.now)
    end_session = models.DateTimeField(default=timezone.now)
    note = models.TextField(blank=True, null=True)
    recurring = models.ForeignKey(RecurringStudySession, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.subject)
    

    

studyplanner/planner/forms.py
from django import forms
from .models import *
from recurrence.forms import RecurrenceField

class SubjectForm(forms.ModelForm):
    class Meta:
        model = subject
        fields=['name', 'color']

class SessionForm(forms.ModelForm):
    class Meta:
        model = studysession
        fields=['subject', 'title', 'start_session', 'end_session', 'note']

studyplanner/planner/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from planner.models import *
from .forms import SubjectForm
from django.urls import reverse
from django.http import JsonResponse
from datetime import datetime, timedelta
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
import json
from django.utils.dateparse import parse_datetime


def subject_list(request):
    subjects = subject.objects.all()
    return render(request, 'index.html', {'subjects': subjects})


def session_list(request):
    subjects = subject.objects.all()
    start_str = request.GET.get('start')
    end_str = request.GET.get('end')
    if start_str and end_str:
        start = timezone.make_naive(parse_datetime(start_str))
        end = timezone.make_naive(parse_datetime(end_str))

    else:
        start = timezone.now().replace(day=1, hour=0, minute=0)
        end = (start + timedelta(days=35)).replace(day=1)

    # تولید جلسات از recurrence
    recurring_sessions = RecurringStudySession.objects.all()

    # skipped_dates_by_recurring = {
    #     s.recurring_id: set()
    #     for s in SkippedOccurrence.objects.all()
    # }
    # for s in SkippedOccurrence.objects.all():
    #     skipped_dates_by_recurring[s.recurring_id].add(s.date)

    for recurring_session in recurring_sessions:
        for recurring_date in recurring_session.recurrence.between(start, end):
            # if date in skipped_dates_by_recurring.get(recurring.id, set()):
            #      continue

            dt_start = datetime.combine(recurring_date, recurring_session.start_time)
            dt_end = datetime.combine(recurring_date, recurring_session.end_time)
            changed_session = SkippedOccurrence.objects.filter(recurring = recurring_session, date = recurring_date)
            if not studysession.objects.filter(
                start_session=dt_start,
                end_session=dt_end,
                recurring=recurring_session
            ).exists() and (len(changed_session) == 0):
                session = studysession(
                title=recurring_session.title,
                subject=recurring_session.subject,
                start_session=dt_start,
                end_session=dt_end,
                recurring=recurring_session
            )
                session.save()

    sessions = list(studysession.objects.filter(start_session__gte=start, end_session__lte=end))
    return render(request, 'session.html', {'sessions': sessions, 'subjects': subjects})





def subject_create(request):
    if request.method == "POST":
        name = request.POST.get("name")
        color = request.POST.get("color")
        if name and color:
            subject.objects.create(name=name, color=color)
    return HttpResponseRedirect(reverse('planner:index'))


def subject_edit(request):
    if request.method == 'POST':
        subject_id = request.POST.get('subject_id')
        item = get_object_or_404(subject, id=subject_id)
        form = SubjectForm(request.POST, instance=item)
        if form.is_valid():
             form.save()
             return HttpResponse('<script>location.reload()</script>')
    return redirect('planner:index')


def delete_subject(request):
    if request.method == 'POST':
        subject_id = request.POST.get("subject_id")
        subj = subject.objects.get(id=subject_id)
        subj.delete()
    return HttpResponseRedirect(reverse('planner:index'))
    

def add_studysession(request):
    if request.method == "POST":
        subject_id = request.POST.get("subject")
        title = request.POST.get("title")
        start = request.POST.get("start_session")
        end = request.POST.get("end_session")
        note = request.POST.get("note")

        subj = subject.objects.get(id=subject_id)
        studysession.objects.create(
            subject=subj,
            title=title,
            start_session=start,
            end_session=end,
            note=note
        )
    return HttpResponseRedirect(reverse('planner:index'))

def delete_session(request):
    if request.method == 'POST':
        session_id = request.POST.get("session_id")
        ses = studysession.objects.get(id=session_id)
        if ses.recurring:
            SkippedOccurrence.objects.get_or_create(
            recurring=ses.recurring,
            date=ses.start_session.date()
            )   
        ses.delete()
    return HttpResponseRedirect(reverse('planner:index'))

def edit_session(request):
    if request.method == "POST":
        session_id = request.POST.get("id")
        session = get_object_or_404(studysession, id=session_id)

        old_date = session.start_session.date()
        if session.recurring:
            new_date = parse_datetime(request.POST.get("start_session")).date()
            if old_date != new_date:
                SkippedOccurrence.objects.get_or_create(
                recurring=session.recurring,
                date=old_date
        )

        # سپس فیلدها رو آپدیت کن
        session.title = request.POST.get("title")
        session.start_session = request.POST.get("start_session")
        session.end_session = request.POST.get("end_session")
        session.note = request.POST.get("note")
        
        # subject
        subject_id = request.POST.get("subject")
        session.subject_id = subject_id


        session.save()

        return redirect("planner:index")


def events_api(request):
    sessions = studysession.objects.all()
    
    events = []
    for s in sessions:

        events.append({
            "id": s.id,
            "title": f"{s.title} ({s.subject.name})",
            "start": s.start_session.isoformat(),
            "end": s.end_session.isoformat(),
            "backgroundColor": s.subject.color,
            "borderColor": s.subject.color,
            "textColor": "#000000",
            "allDay": False,
            "extendedProps": {
                "note": s.note or "",
                "subject": s.subject.name,
                "subject_id": s.subject.id,
            }
        })
    return JsonResponse(events, safe=False)


@csrf_exempt
def update_session_date(request):
    if request.method == "POST":
        data = json.loads(request.body)
        session_id = data.get("id")
        start = parse_datetime(data.get("start"))
        end = parse_datetime(data.get("end"))
    if start and timezone.is_aware(start):
        start = timezone.make_naive(start)

    if end and timezone.is_aware(end):
        end = timezone.make_naive(end)
        try:
            session = studysession.objects.get(id=session_id)
            session.start_session = start
            session.end_session = end if end else start
            session.save()
            return JsonResponse({"status": "ok"})
        except studysession.DoesNotExist:
            return JsonResponse({"error": "Not found"}, status=404)

    return JsonResponse({"error": "Invalid method"}, status=400)


def test(request):
    return render(request, "test.html")

studyplanner/planner/templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_css %}
    <script src="https://unpkg.com/htmx.org@1.9.2"></script>
    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/main.min.css' rel='stylesheet' />

</head>

<body class="h-screen">
    <div class="navbar flex justify-between bg-base-100 shadow-sm">
        <div class="flex-none">
            <label for="my-drawer-2" class="btn btn-square btn-ghost drawer-button">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    class="inline-block h-5 w-5 stroke-current">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
            </label>
        </div>



        <div class="navbar-center">
            <a class="btn btn-ghost text-xl">Studyplanner</a>
        </div>

        <div class="flex">
            <div class="dropdown">
                <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
                    <svg xmlns="https://img.icons8.com/?size=100&id=GvQH0euDgd7J&format=png&color=000000"
                        class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M4 6h16M4 12h8m-8 6h16" />
                    </svg>
                </div>
            </div>
            <div class="flex-none">
                <div class="dropdown dropdown-end">
                    <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar h-15 w-15">
                        <div class="w-10 rounded-full">
                            <img src="{% static 'media/user_menu.png' %}" class="object-fill w-15 h-15" alt="User Menu">
                        </div>
                    </div>
                    <ul tabindex="0"
                        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
                        <li>
                            <a class="justify-between">
                                حساب کاربری
                                <span class="badge">جدید</span>
                            </a>
                        </li>
                        <li><a>تنطیمات</a></li>
                        <li><a>خروچ از حساب کاربری</a></li>
                    </ul>
                </div>
            </div>
        </div>


    </div>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.js'></script>
    {% block content %}
    {% endblock %}
</body>

</html>

studyplanner/planner/templates/session.html
<div class="bg-base-200 text-base-content w-80 pt-3 rounded-box flex flex-col gap-2 overflow-y-auto max-h-[98vh]">
    <button id="add-session-button" class="btn btn-dash btn-xs top-8 right-5"
        hx-get="{% url 'planner:add_studysession' %}" hx-target="#add-session-modal-body" hx-trigger="click"
        onclick="add_session_modal.showModal()">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 stroke-current" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
        </svg>
    </button>
        <div class="flex-grow flex flex-col gap-2 overflow-y-auto
                max-h-[calc(100vh-6rem)]
                md:max-h-none md:overflow-visible pr-1">
    {% for session in sessions %}
    <div class="rounded-xl p-2 text-black shadow" style="background-color: {{ session.subject.color }};">
        <!-- let Tarane figure it out, don't touch.!!!!!! onmouseover="getElementById('{{session.id}}+buttons').classList.remove('hidden');"> -->
        <div class="font-bold text-base">{{ session.subject.name }}</div>
        <div class="text-sm">{{ session.title }}</div>
        <div class="text-xs">{{ session.start_session|time:"H:i" }} - {{ session.end_session|time:"H:i" }}</div>
        <div class="flex justify-end">
            <!-- dast nazar lotfan. male taranst hidden" id="{{ session.id }} + 'buttons'"> -->

            <!--btn edit_session-->
            <button hx-target="#edit-session-modal-body" hx-trigger="click"
                onclick="
                            document.getElementById('edit-session-id').value = '{{ session.id }}';
                            document.getElementById('edit-session-subject').value = '{{ session.subject.id }}';
                            document.getElementById('edit-session-title').value = '{{ session.title }}';
                            document.getElementById('edit-session-start_session').value = '{{ session.start_session|date:"Y-m-d\\TH:i" }}';
                            document.getElementById('edit-session-end_session').value='{{ session.end_session|date:"Y-m-d\\TH:i" }}'
                            ; document.getElementById('edit-session-note').value='{{ session.note|default_if_none:"" }}' ;
                            edit_session_modal.showModal();" 
                class="btn btn-ghost btn-xs">
                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="15" height="15" viewBox="0 0 24 24">
                    <path
                        d="M 19.171875 2 C 18.448125 2 17.724375 2.275625 17.171875 2.828125 L 16 4 L 20 8 L 21.171875 6.828125 C 22.275875 5.724125 22.275875 3.933125 21.171875 2.828125 C 20.619375 2.275625 19.895625 2 19.171875 2 z M 14.5 5.5 L 3 17 L 3 21 L 7 21 L 18.5 9.5 L 14.5 5.5 z">
                    </path>
                </svg>
            </button>

            <!--btn delete_session-->
            <button hx-get="{% url 'planner:delete_session' %}" hx-target="#delete-session-modal-body"
                hx-trigger="click" onclick="document.getElementById('delete-session-id').value = '{{ session.id }}'; 
                            document.getElementById('delete-session-message').textContent = 'Are you sure you want to delete «{{ session.title }}» from «{{ session.subject.name }}» ?'
                            delete_session_modal.showModal();" class="btn btn-ghost btn-xs">
                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="18" height="18" viewBox="0 0 64 64">
                    <path
                        d="M 28 7 C 25.243 7 23 9.243 23 12 L 23 15 L 13 15 C 11.896 15 11 15.896 11 17 C 11 18.104 11.896 19 13 19 L 15.109375 19 L 16.792969 49.332031 C 16.970969 52.510031 19.600203 55 22.783203 55 L 41.216797 55 C 44.398797 55 47.029031 52.510031 47.207031 49.332031 L 48.890625 19 L 51 19 C 52.104 19 53 18.104 53 17 C 53 15.896 52.104 15 51 15 L 41 15 L 41 12 C 41 9.243 38.757 7 36 7 L 28 7 z M 28 11 L 36 11 C 36.552 11 37 11.449 37 12 L 37 15 L 27 15 L 27 12 C 27 11.449 27.448 11 28 11 z M 19.113281 19 L 44.886719 19 L 43.212891 49.109375 C 43.153891 50.169375 42.277797 51 41.216797 51 L 22.783203 51 C 21.723203 51 20.846109 50.170328 20.787109 49.111328 L 19.113281 19 z M 32 23.25 C 31.033 23.25 30.25 24.034 30.25 25 L 30.25 45 C 30.25 45.966 31.033 46.75 32 46.75 C 32.967 46.75 33.75 45.966 33.75 45 L 33.75 25 C 33.75 24.034 32.967 23.25 32 23.25 z M 24.642578 23.251953 C 23.677578 23.285953 22.922078 24.094547 22.955078 25.060547 L 23.652344 45.146484 C 23.685344 46.091484 24.462391 46.835938 25.400391 46.835938 C 25.421391 46.835938 25.441891 46.835938 25.462891 46.835938 C 26.427891 46.801938 27.183391 45.991391 27.150391 45.025391 L 26.453125 24.939453 C 26.419125 23.974453 25.606578 23.228953 24.642578 23.251953 z M 39.355469 23.251953 C 38.388469 23.224953 37.580875 23.974453 37.546875 24.939453 L 36.849609 45.025391 C 36.815609 45.991391 37.571109 46.801938 38.537109 46.835938 C 38.558109 46.836938 38.578609 46.835938 38.599609 46.835938 C 39.537609 46.835938 40.314656 46.091484 40.347656 45.146484 L 41.044922 25.060547 C 41.078922 24.094547 40.321469 23.285953 39.355469 23.251953 z">
                    </path>
                </svg>
            </button>
        </div>
    </div>
    {% empty %}
    <div class="text-sm text-center text-gray-400 mt-10">هیچ برنامه‌ای هنوز ثبت نشده</div>
    {% endfor %}


    <!-- dilog edit_session -->
    <dialog id="edit_session_modal" class="modal">
        <div class="modal-box" id="edit-session-modal-body">
            <h3 class="font-bold text-lg mb-4">Edit Studysession</h3>
            <form method="POST" action="{% url 'planner:edit_session' %}" class="flex flex-col gap-3">
                {% csrf_token %}

                <input type="hidden" name="id" id="edit-session-id">

                <select name="subject" id="edit-session-subject" class="select select-bordered w-full" required>
                    <option disabled>Subject</option>
                    {% for subj in subjects %}
                    <option value="{{ subj.id }}">{{ subj.name }}</option>
                    {% endfor %}
                </select>


                <input type="text" name="title" id="edit-session-title" placeholder="Title"
                    class="input input-bordered w-full" required />
                <input type="datetime-local" name="start_session" id="edit-session-start_session"
                    class="input input-bordered w-full" required />
                <input type="datetime-local" name="end_session" id="edit-session-end_session"
                    class="input input-bordered w-full" required />
                <textarea name="note" id="edit-session-note" class="textarea textarea-bordered"
                    placeholder="Note (optional)"></textarea>

                <div class="modal-action justify-start" dir="rtl">
                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
            </form>
            <form method="dialog">
                <button class="btn btn-sm">Close</button>
            </form>
        </div>
    </dialog>




    <!-- dialog delete_session -->
    <dialog id="delete_session_modal" class="modal">
        <div class="modal-box">
            <h3 class="font-bold text-lg mb-4">Delete Studysession</h3>
            <form method="POST" action="{% url 'planner:delete_session' %}" class="flex flex-col gap-3"
                id="delete-session-form">
                {% csrf_token %}
                <input type="hidden" name="session_id" id="delete-session-id" />
                <p class="text-right" id="delete-session-message">ایا مطمعنید میخواید این درس رو حذف کنید؟</p>
                <div class="modal-action justify-start" dir="rtl">
                    <button type="submit" class="btn btn-error btn-sm">Delete</button>
            </form>
            <form method="dialog">
                <button class="btn btn-sm">Close</button>
            </form>
        </div>
</div>
</dialog>



<!-- dilog add_session -->
<dialog id="add_session_modal" class="modal">
    <div class="modal-box">
        <h3 class="font-bold text-lg mb-4">Add Studysession</h3>
        <form method="POST" action="{% url 'planner:add_studysession' %}" class="flex flex-col gap-3">
            {% csrf_token %}

            <select name="subject" class="select select-bordered w-full" required>
                <option disabled selected>Choose Subject</option>
                {% for subj in subjects %}
                <option value="{{ subj.id }}">{{ subj.name }}</option>
                {% endfor %}
            </select>

            <input type="text" name="title" placeholder="Title" class="input input-bordered w-full" required />
            <input type="datetime-local" name="start_session" class="input input-bordered w-full" required />
            <input type="datetime-local" name="end_session" class="input input-bordered w-full" required />
            <textarea name="note" class="textarea textarea-bordered" placeholder="Note (optional)"></textarea>

            <div class="modal-action flex justify-start" dir="rtl">
                <button type="submit" class="btn btn-primary btn-sm">Save</button>
        </form>
        <form method="dialog">
            <button class="btn btn-sm">Close</button>
        </form>
    </div>
</dialog>
</div>

studyplanner/planner/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
</body>
</html>